-- =====================================================
-- ADMIN TABLE SETUP - Create if not exists
-- =====================================================
-- First, let's create the Admin table if it doesn't exist with proper structure

CREATE TABLE IF NOT EXISTS public."Admin" (
  input_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NULL,
  email text NULL,
  password text NULL,
  role text NULL DEFAULT 'ADMIN',
  department text NULL DEFAULT 'ADMINISTRATION',
  is_active boolean NULL DEFAULT true,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT Admin_pkey PRIMARY KEY (input_id),
  CONSTRAINT Admin_email_key UNIQUE (email)
);

-- =====================================================
-- INSERT ADMIN USER
-- =====================================================
INSERT INTO public."Admin" (name, email, password, role, department, is_active) VALUES
('Super Admin', 'admin@college.edu', 'admin123', 'SUPER_ADMIN', 'ADMINISTRATION', true)
ON CONFLICT (email) DO UPDATE SET 
  name = 'Super Admin',
  password = 'admin123',
  role = 'SUPER_ADMIN',
  department = 'ADMINISTRATION',
  is_active = true;

-- =====================================================
-- VERIFY SETUP
-- =====================================================
SELECT 'Admin Setup Complete!' as status;
SELECT input_id, name, email, role, is_active FROM public."Admin" WHERE email = 'admin@college.edu';
